[package]
name = "nestri-server"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nestri-server"
path = "src/main.rs"

[dependencies]
gst.workspace = true
moq-gst = { git = "https://github.com/wanjohiryan/moq-gst", branch = "main" }
tokio-tungstenite = { version = "0.24.0", features = ["native-tls"] }
serde = {version = "1.0.214", features = ["derive"] }
tokio = { version = "1.41.0", features = ["full"] }
clap = { version = "4.5.20", features = ["env"] }
tracing-subscriber = "0.3"
futures-util = "0.3.31"
serde_json = "1.0.132"
tracing = "0.1.40"
webrtc = "0.11.0"
reqwest = { version = "0.12", features = ["json"] }
regex = "1.11.1"
rand = "0.8.5"
url = "2.5.3"
